#!/bin/bash
# Example: Generate Terraform variable for available regions
# This creates a list of regions where an instance type is available

INSTANCE_TYPE="${1:-m7i.large}"
OUTPUT_FILE="terraform_regions.auto.tfvars"

echo "🔍 Finding regions with ${INSTANCE_TYPE}..."

# Get available regions as JSON array
regions=$(truffle search "${INSTANCE_TYPE}" --output json 2>/dev/null | \
    jq -r '[.[].region] | unique | .[]' | \
    awk '{printf "\"%s\",\n", $0}' | \
    sed '$ s/,$//')

# Generate Terraform variable file
cat > "${OUTPUT_FILE}" << EOF
# Auto-generated by truffle
# Instance type: ${INSTANCE_TYPE}
# Generated: $(date)

available_regions = [
${regions}
]
EOF

echo "✅ Generated ${OUTPUT_FILE}"
echo ""
echo "📄 Content:"
cat "${OUTPUT_FILE}"
echo ""
echo "💡 Use in your Terraform:"
echo "   variable \"available_regions\" { type = list(string) }"
