AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB tables and SNS topics for spawn alerting system'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
    Description: Environment name for resource tagging

Resources:
  SpawnAlertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: spawn-alerts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: alert_id
          AttributeType: S
        - AttributeName: sweep_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: alert_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: sweep_id-index
          KeySchema:
            - AttributeName: sweep_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: user_id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: spawn
        - Key: Component
          Value: alerts

  SpawnAlertHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: spawn-alert-history
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: alert_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: alert_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: user_id-timestamp-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: spawn
        - Key: Component
          Value: alerts

  SweepAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: spawn-sweep-alerts
      DisplayName: Spawn Sweep Alerts
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: spawn
        - Key: Component
          Value: alerts

  ScheduleAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: spawn-schedule-alerts
      DisplayName: Spawn Schedule Alerts
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: spawn
        - Key: Component
          Value: alerts

  CostAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: spawn-cost-alerts
      DisplayName: Spawn Cost Alerts
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: spawn
        - Key: Component
          Value: alerts

Outputs:
  AlertsTableName:
    Description: Name of the alerts table
    Value: !Ref SpawnAlertsTable
    Export:
      Name: !Sub '${AWS::StackName}-alerts-table'

  AlertsTableArn:
    Description: ARN of the alerts table
    Value: !GetAtt SpawnAlertsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-alerts-table-arn'

  AlertHistoryTableName:
    Description: Name of the alert history table
    Value: !Ref SpawnAlertHistoryTable
    Export:
      Name: !Sub '${AWS::StackName}-alert-history-table'

  AlertHistoryTableArn:
    Description: ARN of the alert history table
    Value: !GetAtt SpawnAlertHistoryTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-alert-history-table-arn'

  SweepAlertsTopicArn:
    Description: ARN of the sweep alerts SNS topic
    Value: !Ref SweepAlertsTopic
    Export:
      Name: !Sub '${AWS::StackName}-sweep-alerts-topic'

  ScheduleAlertsTopicArn:
    Description: ARN of the schedule alerts SNS topic
    Value: !Ref ScheduleAlertsTopic
    Export:
      Name: !Sub '${AWS::StackName}-schedule-alerts-topic'

  CostAlertsTopicArn:
    Description: ARN of the cost alerts SNS topic
    Value: !Ref CostAlertsTopic
    Export:
      Name: !Sub '${AWS::StackName}-cost-alerts-topic'
